export const promoENUM = {
  SUPERPROMO: 'superpromo',
  PROMO: 'promo',
  BRAZIL: 'brazil',
  WORLD: 'world',
};

export const data = [
  {
    name: 'Enotel Acqua Club',
    city: 'Porto de Galinhas',
    image: require('./assets/porto-galinhas.jpg'),
    price: 'R$ 1.259',
    type: promoENUM.SUPERPROMO,
    id: 1,
  },
  {
    city: 'Dublin',
    image: require('./assets/dublin.png'),
    type: promoENUM.PROMO,
    price: 'R$ 1.259',
    id: 2,
  },
  {
    city: 'Lisboa',
    image: require('./assets/lisboa.png'),
    type: promoENUM.PROMO,
    price: 'R$ 1.259',
    id: 3,
  },
  {
    city: 'Barcelona',
    image: require('./assets/barcelona.png'),
    type: promoENUM.PROMO,
    price: 'R$ 1.259',
    id: 4,
  },
  {
    city: 'Montevideo',
    image: require('./assets/montevideo.png'),
    type: promoENUM.PROMO,
    price: 'R$ 1.259',
    id: 5,
  },
  {
    city: 'Lima',
    image: require('./assets/lima.png'),
    type: promoENUM.PROMO,
    price: 'R$ 1.259',
    id: 6,
  },

  {
    city: 'Natal',
    image: require('./assets/natal.png'),
    type: promoENUM.BRAZIL,
    price: 'R$ 1.259',
    id: 7,
  },
  {
    city: 'Gramado',
    image: require('./assets/gramado.png'),
    type: promoENUM.BRAZIL,
    price: 'R$ 1.259',
    id: 8,
  },
  {
    city: 'Maceió',
    image: require('./assets/maceio.png'),
    type: promoENUM.BRAZIL,
    price: 'R$ 1.259',
    id: 9,
  },
  {
    city: 'Salvador',
    image: require('./assets/salvador.png'),
    type: promoENUM.BRAZIL,
    price: 'R$ 1.259',
    id: 10,
  },
  {
    city: 'Bonito',
    image: require('./assets/bonito.png'),
    type: promoENUM.BRAZIL,
    price: 'R$ 1.259',
    id: 11,
  },
  {
    city: 'Nova York',
    image: require('./assets/nova-york.png'),
    type: promoENUM.WORLD,
    price: 'R$ 1.259',
    id: 12,
  },
  {
    city: 'Paris',
    image: require('./assets/paris.png'),
    type: promoENUM.WORLD,
    price: 'R$ 1.259',
    id: 13,
  },
  {
    city: 'Madrid',
    image: require('./assets/madrid.png'),
    type: promoENUM.WORLD,
    price: 'R$ 1.259',
    id: 14,
  },
  {
    city: 'Tokio',
    image: require('./assets/tokio.png'),
    type: promoENUM.WORLD,
    price: 'R$ 1.259',
    id: 15,
  },
  {
    city: 'Lagos',
    image: require('./assets/lagos.png'),
    type: promoENUM.WORLD,
    price: 'R$ 1.259',
    id: 16,
  },
];
